--- 
:backgroundrb: 
  :port: 11006
  :ip: 0.0.0.0
:schedules:
  :billing_worker:
    :billing:
      :trigger_args:
        :start: <%= Time.now + 5.seconds %>
        :repeat_interval: <%+ 1.minute %>
