development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Sustainable Websites (DEVELOPMENT)
  admin_email: ivanoats@gmail.com
  
test:
  <<: *non_production_settings
  site_name: SustainableWebsites (TEST)

staging:
  site_url: http://staging.example.com
  site_name: Sustainable Websites (STAGING)
  admin_email: staging@sustainablewebsites.com  
  
production:
  site_url: http://www.sustainablewebsites.com
  site_name: Sustainable Websites
  admin_email: ivan@sustainablewebsites.com 


